export default {
    "destinationAccountName" : "beneficiaryName",
    "destinationAccountNumber" : "beneficiaryAccount",
    "creditAmount" : "amount",
    "amount" : "amount",
    "depositoryIdNumber" : "idNumber",
    "depositoryName" : "depositoryName",
    "depositoryPhone" : "depositoryPhone",
    "depositoryAddress" : "depositoryAddress",
    "message" : "message",
    "destinationAccountCurrency" : "currency",
    "depositoryType" : "depositoryType",
    "idType" : "idType",
    "appointmentId" : "appointmentId",
    "appointmentCode" : "appointmentCode",
    "name" : "name",
    "email" : "email",
    "phoneNumber": "phoneNumber",
    "password": "password",
    "equivalentAmountCurrency":"equivalentAmountCurrency",
    "equivalentAmount":"equivalentAmount",
    // "methodVerification": "methodVerification",
    "=====" : "==== Add new map before this line ===="
}
